13 create makefile
KonstZiv/universal_flash_cards_chatbot pull request #40
Opened 2022-11-16 21:11 UTC by UlkaBo

source - our project diet. It was correct.

2022-11-17 08:21 UTC, ykshatroff commented on app/base_function/translator.py
> +    settings  # noqa !!!used to load the environment variables required for the function get_translateimporta
To avoid this ugly linebreak, place the comment on a separate line before the import.

2022-11-17 08:24 UTC, ykshatroff commented on mypy.ini
> +ignore_missing_imports = True
These lines are unnecessary.

2022-11-19 13:20 UTC, ykshatroff requested changes
The directory `.data/cache` should not be here. Please add it to `.gitignore` and remove from this PR. :)

2022-11-19 13:22 UTC, ykshatroff commented on tests/test_get_translate.py
> +from app.settings import \
Same as in app/base_function/translator.py, can be applied here.

2022-11-25 07:08 UTC, ykshatroff approved these changes

2022-11-30 19:45 UTC, YanaAnisimova commented on app/Makefile
> +	docker-compose exec postgres psql --user $(PROJECT_NAME) --dbname $(PROJECT_NAME)
```suggestion
	docker-compose exec postgres psql --user $(POSTGRES_USER) --dbname $(POSTGRES_DATABASE_NAME)
```
and need to include .env in Makefile.

2022-12-05 08:42 UTC, merged